# Generated by Django 4.2.6 on 2023-10-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentFormPost',
            fields=[
                ('id_incident', models.IntegerField(primary_key=True, serialize=False)),
                ('description_incident', models.TextField()),
                ('statut_incident', models.CharField(max_length=200)),
            ],
        ),
    ]
