# Generated by Django 4.2.6 on 2023-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestmanagementapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTIENT',
            fields=[
                ('nom_foret', models.TextField(primary_key=True, serialize=False)),
                ('nom_organisme', models.TextField()),
                ('nombre_organisme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FORET',
            fields=[
                ('nom_foret', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('localisation', models.TextField()),
                ('density', models.IntegerField()),
                ('superficy', models.IntegerField()),
                ('quantioty_water', models.IntegerField()),
                ('composition_ground', models.TextField()),
            ],
        ),
    ]
