# Generated by Django 4.1 on 2023-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestmanagementapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id_organisme', models.AutoField(primary_key=True, serialize=False)),
                ('nom_organisme', models.TextField(blank=True)),
                ('nutrition', models.TextField(blank=True)),
                ('facteur_emission', models.IntegerField(blank=True)),
                ('quantite_consommee_CO2', models.IntegerField(blank=True, db_column='quantite_consommee_CO2')),
            ],
            options={
                'db_table': 'ORGANISME',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ORGANISM',
        ),
    ]
