# Generated by Django 4.2.6 on 2023-10-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forestmanagementapp2', '0002_contient_foret'),
    ]

    operations = [
        migrations.CreateModel(
            name='GARDE',
            fields=[
                ('id_garde', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_garde', models.TextField()),
                ('prenom_garde', models.TextField()),
                ('adresse_garde', models.TextField()),
                ('num_telephone', models.TextField()),
                ('mail_garde', models.TextField()),
                ('date_embauche', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='INCIDENT',
            fields=[
                ('id_incident', models.IntegerField(primary_key=True, serialize=False)),
                ('description_incident', models.TextField()),
                ('statut_incident', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MISSION',
            fields=[
                ('id_mission', models.IntegerField(primary_key=True, serialize=False)),
                ('description_mission', models.TextField()),
                ('etat_mission', models.TextField()),
                ('id_garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestmanagementapp2.garde')),
            ],
        ),
        migrations.CreateModel(
            name='ORGANISM',
            fields=[
                ('nom_organisme', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('nutrition', models.TextField()),
                ('facteur_emission', models.IntegerField()),
                ('quantite_consomméé_CO2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='IncidentFormPost',
        ),
        migrations.RenameField(
            model_name='foret',
            old_name='composition_ground',
            new_name='composition_sol',
        ),
        migrations.RenameField(
            model_name='foret',
            old_name='density',
            new_name='densite',
        ),
        migrations.RenameField(
            model_name='foret',
            old_name='quantioty_water',
            new_name='quantite_eau',
        ),
        migrations.RenameField(
            model_name='foret',
            old_name='superficy',
            new_name='superfice',
        ),
        migrations.AlterField(
            model_name='contient',
            name='nom_foret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forestmanagementapp2.foret'),
        ),
        migrations.AddField(
            model_name='garde',
            name='nom_foret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestmanagementapp2.foret'),
        ),
        migrations.AlterField(
            model_name='contient',
            name='nom_organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestmanagementapp2.organism'),
        ),
        migrations.CreateModel(
            name='TOUCHE',
            fields=[
                ('id_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forestmanagementapp2.incident')),
                ('date_incident', models.TextField()),
                ('nom_foret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestmanagementapp2.foret')),
            ],
        ),
        migrations.CreateModel(
            name='POSSEDE',
            fields=[
                ('id_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forestmanagementapp2.mission')),
                ('date_mission', models.TextField()),
                ('etat_mission', models.TextField()),
                ('id_garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestmanagementapp2.garde')),
            ],
        ),
    ]
