# Generated by Django 4.1 on 2023-11-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forestmanagementapp2', '0003_authuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
